# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test_iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build-StackKnowledge-iOS
      run: |  
        xcodebuild clean test -project Stack-Knowledge-iOS.xcodeproj \
        -scheme Stack-Knowledge-iOS \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
